version: '3.8'

services:
  mocky-app:
    #build: .
    image: robdom01/mocky:1.0

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
    ports:
      - ${PUERTO_APP}:8080
    networks:
      - red-app
    depends_on:
      - mysql-db

  mocky-frontend:
    #build: ./frontend
    image: robdom01/mocky_front:1.0

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
    ports:
      - ${PUERTO_FRONT}:3000
    networks:
      - red-app
    depends_on:
      - mocky-app

  mysql-db:
    image: mysql:8.0.27

    env_file:
      - .env

    environment:
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - red-app

  phpmyadmin:
    image: phpmyadmin:5.1.1
    env_file:
      - .env
    ports:
      - ${PUERTO_PHPMYADMIN}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=$DB_HOST
      - PMA_USER=root
      - PMA_PASSWORD=$DB_PASSWORD
      - PMA_PORT=$DB_PORT
    networks:
      - red-app
    depends_on:
      - mysql-db

networks:
  red-app:

volumes:
  db_volume: