version: '3.8'

services:

# HAProxy CONTAINER
  running-haproxy:
    #build: ./HAProxyConfig

    image: robdom01/haproxy:1.0

    container_name: "running-haproxy"

    ports:
      - "80:80"
    networks:
      - red-app
    depends_on:
      - mocky-frontend1

#BACKEND CONTAINER
  mocky-app1:
    #build: .
    image: robdom01/mocky:1.2

    container_name: "mocky-app1"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PUERTO_APP=${PUERTO_APP1}
    ports:
      - ${PUERTO_APP1}:${PUERTO_APP1}
    networks:
      - red-app
    depends_on:
      - mysql-db
  mocky-app2:
    #build: .
    image: robdom01/mocky:1.2

    container_name: "mocky-app2"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PUERTO_APP=${PUERTO_APP2}
    ports:
      - ${PUERTO_APP2}:${PUERTO_APP2}
    networks:
      - red-app
    depends_on:
      - mysql-db

  mocky-app3:
    #build: .
    image: robdom01/mocky:1.2

    container_name: "mocky-app3"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PUERTO_APP=${PUERTO_APP3}
    ports:
      - ${PUERTO_APP3}:${PUERTO_APP3}
    networks:
      - red-app
    depends_on:
      - mysql-db

# FRONTEND CONTAINERS
  mocky-frontend1:
    #build: ./frontend
    image: robdom01/mocky_front:1.0

    container_name: "mocky-frontend1"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PORT=${PUERTO_FRONT1}
      - API_PORT=${PUERTO_APP1}
    ports:
      - ${PUERTO_FRONT1}:${PUERTO_FRONT1}
    networks:
      - red-app
    depends_on:
      - mocky-app1

  mocky-frontend2:
    #build: ./frontend
    image: robdom01/mocky_front:1.0

    container_name: "mocky-frontend2"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PORT=${PUERTO_FRONT2}
      - API_PORT=${PUERTO_APP2}
    ports:
      - ${PUERTO_FRONT2}:${PUERTO_FRONT2}
    networks:
      - red-app
    depends_on:
      - mocky-app2

  mocky-frontend3:
    #build: ./frontend
    image: robdom01/mocky_front:1.0

    container_name: "mocky-frontend3"

    env_file:
      - .env
    environment:
      - NOMBRE_APP=$AMBIENTE
      - PORT=${PUERTO_FRONT3}
      - API_PORT=${PUERTO_APP3}
    ports:
      - ${PUERTO_FRONT3}:${PUERTO_FRONT3}
    networks:
      - red-app
    depends_on:
      - mocky-app3

# DB CONTAINERS
  mysql-db:
    image: mysql:8.0.27

    container_name: "mysql-db"

    env_file:
      - .env

    environment:
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - red-app

  phpmyadmin:
    image: phpmyadmin:5.1.1

    container_name: "phpmyadmin"

    env_file:
      - .env
    ports:
      - ${PUERTO_PHPMYADMIN}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=$DB_HOST
      - PMA_USER=root
      - PMA_PASSWORD=$DB_PASSWORD
      - PMA_PORT=$DB_PORT
    networks:
      - red-app
    depends_on:
      - mysql-db

networks:
  red-app:

volumes:
  db_volume: